tijlleenders/ZinZen

- js/clickhandlers/modalClickHandlerAdd.js
- js/custom.js
- js/helpers.js
Show hints to help schedule a goal.
When it has a duration, give feedback on scheduled status and first slot.
> Scheduling feedback

- js/clickhandlers/modalClickHandlerAdd.js
- js/helpers.js
Simplified title logic by coupling the language to the goal.
> Remove title translations

- js/clickhandlers/modalClickHandlerAdd.js
- js/custom.js
- js/helpers.js
When editing a goal, scheduling tasks and slots will occur in temp collections.
Still todo: Show differences and possible side-effects of changing goal constraints.
When saved, this new situation is persisted.
> Schedule while typing

- js/clickhandlers/modalClickHandlerAdd.js
- js/custom.js
- js/helpers.js
Auto-command 'at X' where X = 0 to 24
It will create separate slots for every day if multiple possible between start and finish range.
However each slot fits exactly one duration so the scheduler *has* to start exactly *at* the specified hour.
> Calendar command at

- css/custom.css
- js/clickhandlers/clickhandlers.js
- js/helpers.js
> Slot collapse

- js/clickhandlers/modalClickHandlerAdd.js
- js/helpers.js
Show color tag for goal and cycle through colors on click.
> Show color tag

- public/index.html
- public/manifest.json
- src/components/Dashboard.js
- src/components/HeaderDashboard.js
- src/components/Title-panel-left.js
- src/components/UserChoiceDashboard.js
- src/customize.scss
- src/translations/en/translation.json
- src/translations/es/translation.json
- src/translations/fr/translation.json
- src/translations/hi/translation.json
- src/translations/nl/translation.json
Added translations for dashboard #65 
Resolved error 404 #67
> Add translations for Dashboard and resolved 404 error

- src/App.css
- src/components/Header.js
- src/components/ImageIconPanelMiddle.js
Made the navbar menu for mobile functional #71
> Make menu button on mobile functional

- src/App.css
- src/components/Dashboard.js
- src/components/HeaderDashboard.js
Made the menu button for mobile functional #71
> Changes in CSS for mobile view

- src/App.css
- src/components/Header.js
Added cypress test for ZinZen logo
> Cypress test add

- .github/workflows/workflow.yml
- cypress.json
- src/App.js
- src/components/dashboard/UserChoiceDashboard.js
- src/components/dashboard/dashboard.scss
- src/components/landingpage/landingpage.scss
- src/components/languagechoices/LangItem.jsx
- src/components/themechoicepage/ThemesChoice.js
- src/components/themechoicepage/themechoice.scss
Fire up CI only when PRs are created #131
> Change workflow.yml to fire up CI only when PRs are created

- .github/workflows/workflow.yml
Added run exceptions in the CI/CD #129
> Add run exceptions in the CI/CD

- src/App.js
- src/components/404page/NotFoundPage.js
- src/components/404page/errorPage.scss
> Make a catchall 404 page

- .github/workflows/cypress.yml
The cypress test is failing, it might be because of the change in versions
> Change cypress test

- src/App.js
- src/components/languagechoices/LangItem.jsx
- src/components/themechoicepage/ThemesChoice.js
> Fix logged in router 404 and resolve warnings

- src/components/404page/NotFoundPage.js
- src/components/dashboard/HeaderDashboard.js
- src/components/dashboard/dashboard.scss
- src/components/landingpage/Header.js
- src/components/themechoicepage/HeaderThemeChoice.js
Removed the menu from the navigation bar and now the logo or the ZinZen link on the navbar redirects to the homepage.
#148
> Add navigation bar functionalities

- src/components/zinzen-menu/ZinZenMenu.jsx
- src/components/zinzen-menu/zinzenmenu.scss
Aligned The button for the menu after clicking ZinZen to the center
> Align ZinZen menu button center

- package-lock.json
- src/components/dashboard/UserChoiceDashboard.jsx
Fixes #240. Removed + functionality on 'My time', 'Explore' and 'ZinZen'.
> Removed + functionality

- src/components/dashboard/UserChoiceDashboard.jsx
- src/components/dashboard/dashboard.scss
I have updated the CSS as asked.
> Style Update

- src/components/dashboard/HeaderDashboard.jsx
> Theme switcher now saves states

- package-lock.json
- src/components/feedbackpage/FeedbackPage.jsx
- yarn.lock
> Fix: Rating Bug in Feedback Page

- src/components/themechoicepage/ThemesChoice.jsx
> Fix startup theme selection

- package.json
> Add Prettier and ESLint Pre-Commit Hooks

- src/components/languagechoices/LangItem.tsx
- src/components/myfeelingspage/AddFeelingsChoices.tsx
- src/components/myfeelingspage/ShowFeelingTemplate.tsx
- src/components/themechoicepage/ThemesChoice.tsx
- src/components/todoList/TodoListForm.tsx
- src/models/index.ts
- yarn.lock
Resolves #286  and Fixed some more import warnings
> Rendering Bug 

- src/api/GoalsAPI/index.ts
- src/models/GoalItem.ts
- src/models/db.ts
- src/models/index.ts
> API implementation for Goals CRUD Operations  

- src/api/GoalsAPI/index.ts
- src/models/index.ts
> Fix import &  export error of GoalItem interface

- src/pages/ExplorePage/ExplorePage.tsx
- src/translations/de/translation.json
- src/translations/en/translation.json
- src/translations/es/translation.json
- src/translations/fr/translation.json
- src/translations/hi/translation.json
- src/translations/nl/translation.json
> Explore Page is now available in all languages

- src/App.tsx
- src/api/FeelingsAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/pages/AddFeelingsPage/AddFeelingsChoices.tsx
- src/pages/FeedbackPage/FeedbackPage.tsx
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
> Convert in TS : ShowFeelingsPage & Api Calls

- src/pages/ExplorePage/ExplorePage.tsx
- src/pages/ExplorePage/explorepage.scss
> Fix: Design of Explore Page

- cypress/integration/explore-page.spec.ts
- cypress/integration/zinzen-page.spec.ts
> Tests for ZinZen page added 

- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/pages/ShowFeelingsPage/ShowFeelingsPage.scss
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
Resolves #408 
Resolves #409 
Resolves #410
> Fix: myFeelingsPage UI Issues  

- src/pages/MyGoalsPage/MyGoalsPage.scss
> Fix: Goal Title Align left & Cursor is pointer

- src/api/FeelingsAPI/index.ts
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
- src/utils/index.ts
> MyFeelings Page : Code Clean and Bug fix

- .github/workflows/cypress.yml
- cypress.config.ts
- cypress.json
- cypress/integration/dashboard.spec.ts
- cypress/integration/explore-page.spec.ts
- cypress/support/e2e.ts
- package-lock.json
- package.json
- src/api/FeelingsAPI/index.ts
- src/pages/ExplorePage/ExplorePage.tsx
- src/pages/ExplorePage/explorepage.scss
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
- src/utils/index.ts
- yarn.lock
> Update: Cypress version and UI Tests

- src/api/FeelingsAPI/index.ts
- src/pages/AddFeelingsPage/AddFeelingTemplate.tsx
- src/pages/AddFeelingsPage/AddFeelingsPage.scss
- src/pages/AddFeelingsPage/AddFeelingsPage.tsx
> Implemented: Deisgn Modifications in addFeelingsPage

- src/api/GoalsAPI/index.ts
- src/models/GoalItem.ts
- src/models/db.ts
- src/pages/AddFeelingsPage/AddFeelingTemplate.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
Resolves #425 
Part of #424, issue to be completed with @Tushar-4781's work on the issue, this PR has no dependency on that
NOTE: This PR will bring breaking changes to the indexdDB storage and interaction. We can discuss the implementation of a migration feature to avoid such changes in the future
> Extend Goals DB

- .eslintrc.json
- .gitignore
- src/components/GoalsComponents/GoalsForm.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Feature/goals UI and validation fixes

- cypress/integration/dashboard.spec.ts
Resolves #456
Added a wait command in the test so that cypress will wait while redirect happens
> Fix: Dashboard Failing TC

- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/index.ts
Resolves #476
I have kept this function in MyTime Page for now. Since that one is in progress. It would prevent unnecessary navigation while testing. Kindly navigate to MyTimePage to initiate the call. 
PS: Just want to keep development fast XD
> Function for populating dummy goals

- src/components/GoalsComponents/GoalsForm.tsx
- src/pages/Dashboard/Dashboard.scss
Fix right border in header bug
> Toggle btn right margin

- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
> Developed: Timeline Task options 

- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/index.ts
Resolves #493 
Resolves #501 
Resolves #502
> Patch: MyTimePage UI/UX 

- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.tsx
> Patch/My Timeline default UI

- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Developed: Sharing Goals Feature UI

- cypress/integration/dashboard.spec.ts
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
> Removed: Auto-redirect from MyFeelingsPage

- cypress/integration/dashboard.spec.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Removed: Auto-redirect from MyGoalsPage

- cypress/integration/Feelings.spec.ts
> Tests for AddFeelings and MyFeelings 

- cypress/integration/Feelings.spec.ts
- src/components/GoalsComponents/GoalsComponents.scss
- src/components/GoalsComponents/GoalsForm.tsx
- src/pages/AddGoalsPage/AddGoalsPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/index.ts
> Updated the Code to use the new Color Pallete  

- src/__tests__/GoalParser.test.ts
- src/components/GoalsComponents/GoalsForm.tsx
Reverts tijlleenders/ZinZen#540
Had to do this as this PR is causing the AddGoal page to become unavailable.
> Revert "433 detect url in goal parser"

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Fix: Null value inplace of magic in Update Goal

- src/components/GoalsComponents/UpdateGoal/UpdateGoal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/utils/index.ts
> Patch: UX of interacting with Goal Color

- src/components/GoalsComponents/UpdateGoal/UpdateGoal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/models/GoalItem.ts
> Update: Weekly as a repetition value in Update Goal page 

- cypress/integration/Feelings.spec.ts
- src/Interfaces/ILanguage.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.scss
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/models/GoalItem.ts
- src/translations/i18n.ts
> Language Tag Visible while adding/updating goal

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Added: URL in goal tile in MyGoals & their sublist

- src/components/GoalsComponents/AddGoal/AddGoalForm.scss
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.scss
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
Resolves #557
Resolves #558
Resolves #584
> Integrated: Goal Timing ( Start & Deadline ) magic 

- src/Interfaces/ISchedulerInputGoal.ts
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.tsx
Resolves #533 
Currently, the Scheduler integrated is dependent on a sample test case that has been written on the MyTime page. The scheduler isn't ready for taking input from the Goals DB.
> Integrated: Scheduler on MyTime Page

- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Added & Integrated: Endpoint of Sharing Goal anonymously

- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
> Fix: Display goals in Suggestions popup modal

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: Show Drop-down if goal has empty sublist

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Navigation from task on MyTimePage to respective goal

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
> Feature added: Add/Remove tag in add/Update Goals page

- src/Interfaces/ISharedGoal.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: Suggestions in Public Goals tab

- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: Archiving Goals till n-level of a goal

- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: Suggestion from MyArchive based on parent

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Patch: Goal Expand icon flipped

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
> Patch: triming the spaces from string values in add/update goals

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
> Fix: Disable autoComplete for goal input field while editing 

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
> Update: Allow goals to be added without duration

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: navigate & show input in goal sublist if add a subgoal choice is made

- src/components/GoalsComponents/AddGoal/AddGoalForm.scss
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/InputGoal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.scss
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/store/GoalsHistoryState.ts
> Update: Added change goal color btn below add/update goal input field 

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/AddGoalOptions.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/InputGoal.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/components/HeaderDashboard/HeaderDashboard.scss
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/store/GoalsState.ts
> Update: goal suggestions popup UI

- src/components/GoalsComponents/InputGoal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.scss
> Update: dashed border input while editing the goal

- src/App.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/pages/ContactsPage/Contacts.scss
- src/pages/ContactsPage/Contacts.tsx
> Update: Contacts Page & Share modal UI

- cypress/integration/myGoals-page.spec.ts
- src/__tests__/GoalParser.test.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/helpers/GoalRepeatHandler.ts
- src/helpers/GoalTimingHandler.ts
- src/pages/ContactsPage/Contacts.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Written: Cypress Tests for MyGoals page & Jest Tests for Goal Parser 

- src/Interfaces/ISharedGoal.ts
- src/Interfaces/ITagExtractor.ts
- src/__tests__/GoalParser.test.ts
- src/api/GoalsAPI/index.ts
- src/helpers/GoalDurationHandler.ts
- src/helpers/GoalRepeatHandler.ts
- src/helpers/GoalTimingHandler.ts
- src/helpers/TagsExtractor.ts
- src/models/GoalItem.ts
> Added:  every x hrs/days patterns

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
> Update: sharing subgoal with parent goal name instead of root

- src/pages/MyTimePage/MyTimePage.tsx
> Fix: My Time page not rendering

- src/api/GoalsAPI/index.ts
> Fix: Only non-null values in share goal object

- src/components/GoalsComponents/InputGoal.tsx
> Patch: Setting cursor to beginning for update goal

- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> On deleting a goal remove it from archive as well && if archived remove it from parent sublist  

- src/components/MyTimeComponents/MyTimeline.tsx
- src/models/GoalItem.ts
- src/models/TaskItem.ts
- src/pages/MyTimePage/MyTimePage.tsx
> Update: Sync. of scheduler o/p with MyTime Page

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
> Removed: husky

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
Reverts tijlleenders/ZinZen#770
> Revert "Removed: husky"

- src/App.tsx
- src/Interfaces/ISchedulerInputGoal.ts
- src/Interfaces/ISharedGoal.ts
- src/api/ContactsAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/AddGoalOptions.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/components/MyTimeComponents/MyTimeline.tsx
- src/models/ContactItem.ts
- src/models/GoalItem.ts
- src/models/TaskItem.ts
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/MyTimePage/MyTimePage.tsx
- src/store/GoalsState.ts
> Feature: Share Root goal 1:1

- src/App.tsx
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/HeaderDashboard/LandingHeader.tsx
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/components/MyTimeComponents/MyTimeline.tsx
- src/constants/booleanScreen.ts
- src/pages/AddFeelingsPage/AddFeelingTemplate.tsx
- src/pages/AddFeelingsPage/AddFeelingsPage.tsx
- src/pages/FAQPage/FAQPage.scss
- src/pages/FAQPage/FAQPage.tsx
- src/pages/FeedbackPage/FeedbackPage.tsx
- src/pages/FeedbackPage/feedbackpage.scss
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/NotFoundPage/NotFoundPage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
> Patch: UI bugs fixed

- package-lock.json
- package.json
- src/App.scss
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/HeaderDashboard/HeaderDashboard.scss
- src/components/HeaderDashboard/LandingHeader.tsx
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/components/Sidebar.tsx
- src/pages/FAQPage/FAQPage.tsx
- src/pages/FeedbackPage/FeedbackPage.tsx
- src/pages/FeedbackPage/feedbackpage.scss
- src/pages/InvitePage/InvitePage.tsx
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/store/SidebarState.ts
> Feature: Implemented Sidebar

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
> Update: Limit on sharing goal with contact and adding contact

- src/App.scss
- src/components/HeaderDashboard/HeaderDashboard.scss
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
> Theme & Layout update: My time page

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/HeaderDashboard/LandingHeader.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Fix: Navigation disabled from ZinZen text logo in sidebar

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Theme color pallete update on my goals

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Patch: Dark and light theme colors for icons in goals options

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> patch: increased the space between inner circle and outer border of leaf

- src/App.scss
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/components/HeaderDashboard/HeaderDashboard.scss
- src/components/HeaderDashboard/LandingHeader.tsx
- src/components/Sidebar.tsx
- src/constants/booleanScreen.ts
- src/pages/FAQPage/FAQPage.tsx
- src/pages/FeedbackPage/FeedbackPage.tsx
- src/pages/FeedbackPage/feedbackpage.scss
- src/pages/LandingPage/LandingPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/pages/ThemeChoice/ThemeChoice.scss
- src/pages/ThemeChoice/ThemeChoice.tsx
> Update: Implement changes in New Theme 

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Fix: Navigation via goal tile

- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> update: Display add Goal options instead of add goal if there is no sublist

- src/pages/FeedbackPage/FeedbackPage.tsx
> patch: default feedback rating as 3.0

- src/components/GoalsComponents/AddGoalOptions.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/store/index.ts
> update: show the add from archive optn if archive for the goal exist 

- src/constants/starterGoals.ts
- src/pages/MyTimePage/MyTimePage.tsx
> Update: Starter Goals for new users 

- src/components/LanguageChoice/LangItem.tsx
- src/pages/FAQPage/FAQPage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/pages/ThemeChoice/ThemeChoice.tsx
> Feature: vibrate on selecting a choice on starter pages

- src/App.scss
- src/App.tsx
- src/common/Loader.tsx
- src/components/GoalsComponents/AddGoalOptions.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/store/index.ts
> Update: Raising Toast in hint option if no goals are there 

- src/utils/index.ts
Added the new colors for goals as discussed in #846
> add new colors for goals

- src/components/MyTimeComponents/MyTimeline.scss
- src/pages/MyTimePage/MyTimePage.tsx
Resolves #836 
Resolves #854 
Resolves #853
> Update: My Time page & scheduler sync

- src/App.scss
- src/App.tsx
- src/api/ContactsAPI/index.ts
- src/components/GoalsComponents/ShareGoalModal/InviteLinkModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/components/HeaderDashboard/LandingHeader.tsx
- src/models/ContactItem.ts
- src/models/db.ts
- src/pages/FAQPage/FAQPage.tsx
- src/pages/InvitePage/InvitePage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/store/index.ts
Resolves #839 
Resolves #856
part of #779
> Update: Sharing and Invite modal as per new UI

- src/App.scss
- src/App.tsx
- src/api/ContactsAPI/index.ts
- src/components/GoalsComponents/GoalInvites/GoalInvites.tsx
- src/components/GoalsComponents/ShareGoalModal/InviteLinkModal.tsx
- src/components/Sidebar.tsx
- src/models/ContactItem.ts
- src/models/db.ts
Resolves #863 
Currently, it shows all the goals in "shared with me". the logic of collab invites will be released in the following PR which targets #747. The collab logic is still in the developing phase. but the UI is ready so we can merge this. You might see shared goals again after refreshing regardless of adding or ignoring them. because the entire share 1:1 feature is in dev mode I need goals. we can fix by removing a small check. Hence, it's not a bug.
> Feature: Sidebar invites tab

- src/pages/MyTimePage/MyTimePage.tsx
> update: passing duration as string in Scheduler

- src/components/LanguageChoice/LangItem.tsx
- src/constants/vibrateCheck.ts
- src/pages/FAQPage/FAQPage.tsx
- src/pages/QueryPage/QueryPage.tsx
- src/pages/ThemeChoice/ThemeChoice.tsx
Hi Tushar, the issue #842 has been resolved in this branch. Please review. It has been tested on iphone 14(safari version 16.1) and on Mac safari.
> App works on safari now

- src/App.scss
Hi Tushar, the issue #862 has been resolved in this branch. Please review it.
> Resolves issue - Fixed size background gradient

- src/App.tsx
- src/Interfaces/ICollaboration.ts
- src/Interfaces/IShared.ts
- src/Interfaces/ISharedGoal.ts
- src/api/ContactsAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/GoalInvites/GoalInvites.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/ShareGoalModal/InviteLinkModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal.tsx
- src/constants/starterGoals.ts
- src/helpers/CollaborationHandler.ts
- src/helpers/GoalConvertor.ts
- src/models/GoalItem.ts
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/MyTimePage/MyTimePage.tsx
- src/translations/i18n.ts
- src/utils/index.ts
Resolves #886 
Resolves #885 
Resolves #535
> Update: New GoalItem schema to keep colab and share details independent 

- src/helpers/TaskFilter/TaskFilter.test.ts
- src/helpers/TaskFilter/TaskFilter.ts
> Add helper module that filters tasks according to start day.

- src/App.tsx
- src/Interfaces/ICollaboration.ts
- src/api/GoalsAPI/index.ts
- src/api/OutboxAPI/index.ts
- src/common/NotificationSymbol.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/GoalInvites/GoalInvites.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/ShareGoalModal/InviteLinkModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/helpers/CollaborationHandler.ts
- src/models/GoalItem.ts
- src/models/OutboxItem.ts
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/utils/index.ts
This needs a bit of hard review/Testing. 
Resolves #883
> Update: Colab Feature v2 

- src/api/ContactsAPI/index.ts
> Fix: api(s) using installId not working

- src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsHeader/GoalsHeader.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
Resolves #909 
Spotted Issue: Enter works like a submit button which was calling another function having the same code of adding/updating ( like in my goals which is called by check ) but it didn't contain the part of sending an update. 
The solution in the PR: Removed the redundancy of the functions by passing the add/update goal function as props
> Update: Goal not being shared when pressed Enter for adding/updating

- src/Interfaces/ILanguage.ts
- src/components/LanguageChoice/LangItem.tsx
- src/components/LanguageChoice/LanguageChoice.scss
- src/customize.scss
- src/pages/LandingPage/LandingPage.tsx
Hi Tushar, the feature mentioned in #843 has been completed and tested for english, hindi, french, portugese and dutch. It has been complete on the functional level as well as the UI level. Please have a look.
> Make browser lang the first choice and highlight feature completed

- src/App.tsx
- src/api/ContactsAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/AddGoalOptions/AddGoalOptions.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/GoalInvites/GoalInvites.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/InputGoal.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/InviteLinkModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal/SuggestionModal.tsx
- src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
- src/constants/starterGoals.ts
- src/helpers/GoalController.ts
- src/helpers/GoalProcessor.ts
- src/pages/InvitePage/InvitePage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/services/contact.service.ts
- src/services/goal.service.ts
- src/utils/index.ts
This PR was required to created base of incoming features on MyGoals page
> Restructuring | Refractoring | Cleaning of files & dir(s) connected to MyGoals

- src/Interfaces/Task.ts
- src/components/MyTimeComponents/MyTimeline.tsx
- src/helpers/TaskFilter/TaskFilter.ts
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
> Feature: Weekly schedule on MyTime Page

- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
> Feature: Show impossible tasks on MyTime page for everyday

- src/pages/MyGoalsPage/MyGoalsPage.tsx
> update: keep inbox on right

- src/pages/MyGoalsPage/MyGoalsPage.tsx
> fix: refresh goals once deletion is done

- src/components/GoalsComponents/SuggestionModal/SuggestionModal.scss
- src/components/GoalsComponents/SuggestionModal/SuggestionModal.tsx
> fix: change goal title color to black in suggestions

- src/api/ContactsAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/api/SharedWMAPI/index.ts
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: goals sorted by createdAt parameter

- src/App.tsx
- src/Interfaces/ICollaboration.ts
- src/Interfaces/IDisplayChangesModal.ts
- src/Interfaces/IShared.ts
- src/api/GoalsAPI/index.ts
- src/api/InboxAPI/index.ts
- src/api/PubSubAPI/index.ts
- src/api/SharedWMAPI/index.ts
- src/components/GoalsComponents/DisplayChangesModal/AcceptBtn.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/DisplayChangesModal/Header.tsx
- src/components/GoalsComponents/DisplayChangesModal/IgnoreBtn.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/helpers/GoalController.ts
- src/helpers/GoalProcessor.ts
- src/helpers/InboxProcessor.ts
- src/helpers/OutboxProcessor.ts
- src/models/InboxItem.ts
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/services/contact.service.ts
- src/store/GoalsState.ts
- src/utils/index.ts
> Feature: Collaboration with new DB design and better UX

- src/components/HeaderDashboard/HeaderDashboard.scss
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
> Patch: header icons modifications

- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.tsx
> Fix: color bands width distribution | Update: day starts and end on 0:00

- src/components/Sidebar.tsx
> Removed MyFeelings from side menu

- src/api/GoalsAPI/index.ts
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/pages/MyTimePage/MyTimePage.tsx
> Feature: dev mode

- src/components/GoalsComponents/MyGoal.tsx
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/store/index.ts
> Update: Goals Search bar layout and Working

- src/api/GoalsAPI/index.ts
- src/api/SharedWMAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/helpers/InboxProcessor.ts
> Feature: show archived goals in sublist in strike-through style 

- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.tsx
> Update: Show drop down icon to close task card 

- src/api/GoalsAPI/index.ts
- src/api/SharedWMAPI/index.ts
- src/components/GoalsComponents/AddGoalOptions/AddGoalOptions.tsx
- src/components/GoalsComponents/ArchivedAccordion/ArchivedAccordion.tsx
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/global.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Feature: Drawer at bottom to see archived goals 

- src/services/contact.service.ts
I did an experiment to see if I could deploy the URL endpoint independently of the Lambda...
Unfortunately this doesn't work - so we'll have to keep changing the URLs every time a redeploy is required... :/
> update relationship endpoint

- package.json
- src/components/Sidebar.tsx
- src/global.scss
> Added: Theme Switcher in sidebar

- index.html
Fixes Lighthouse PWA error for IOS installability.
> fix lighthouse apple-touch-icon error

- src/App.tsx
- src/Interfaces/IPages.ts
- src/Interfaces/IPopupModals.ts
- src/common/ConfirmationModal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/AddContactModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/components/GoalsComponents/SuggestionModal/SuggestionModal.tsx
- src/constants/confirmationHeaders.ts
- src/pages/AddFeelingsPage/AddFeelingTemplate.tsx
- src/pages/AddFeelingsPage/AddFeelingsPage.tsx
- src/pages/InvitePage/InvitePage.tsx
- src/pages/LandingPage/LandingPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/store/DarkModeState.ts
- src/store/index.ts
Resolves #1032 
Resolves #1033
> Feature: Confirmation popup on goal actions

- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyTimePage/MyTimePage.tsx
> Integrated: New scheduler build 

- src/pages/MyTimePage/MyTimePage.tsx
> fix: Undefine free hrs on myTimeline | update: show free slots in color bands

- src/common/Search.tsx
> added: auto focus in search bar

- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/index.ts
Resolves #1048
This pull request updates the MyTime component to display today's date in the format "Saturday 25th", where "Saturday" is the long name of the day of the week, and "25th" is the day of the month with "th" in superscript. This formatting will only apply to today's date.
> Update MyTime component to display today's date with day name and day number #1048

- src/App.tsx
- src/Interfaces/IDisplayChangesModal.ts
- src/api/SharedWMAPI/index.ts
- src/components/GoalsComponents/DisplayChangesModal/AcceptBtn.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/DisplayChangesModal/IgnoreBtn.tsx
- src/components/GoalsComponents/ShareGoalModal/AddContactModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/helpers/GoalProcessor.ts
- src/helpers/InboxProcessor.ts
- src/pages/MyTimePage/MyTimePage.tsx
Resolves #1050 
Resolves #1051
> Update: Allow selecting changes in collaboration

- src/pages/MyTimePage/MyTimePage.tsx
- src/validators/GoalValidators.ts
> Update: MyTime shows all goals | New addition in dev mode

- src/helpers/GoalRepeatHandler.ts
- src/pages/MyTimePage/MyTimePage.tsx
> New Update: Weekdays and Weekends tag available in goal parser under repeat

- src/Interfaces/ISchedulerInputGoal.ts
- src/components/GoalsComponents/InputGoal.tsx
- src/components/GoalsComponents/SuggestionModal/SuggestionModal.tsx
- src/constants/starterGoals.ts
- src/helpers/GoalProcessor.ts
- src/helpers/MiniScheduler.ts
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/SchedulerUtils.ts
- src/utils/index.ts
- src/validators/GoalValidators.ts
<-- Desperate Times Calls For Desperate Measures --> 
If this works fine then we can say we have a backup for our demo. hehehe...
PS: Please Ignore typescript warnings that are not handled.
> Feature: scheduler made in JS 

- src/components/HeaderDashboard/MainHeaderDashboard.tsx
> Selected icon highlighter in header

- src/components/HeaderDashboard/HeaderDashboard.scss
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
> update: subtext in header below icons

- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.scss
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/constants/myGoals.ts
Resolves #1075 
Resolves #1077 
Resolves #1082
> Update: Duration & budget cannot exist together

- src/pages/MyTimePage/MyTimePage.tsx
Resolves #1071 
Resolves #1076
> patch: integrating Rust scheduler

- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.scss
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
> update: dark theme of config modal implemented

- src/api/TasksAPI/index.ts
- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/models/TaskItem.ts
- src/models/db.ts
- src/pages/MyTimePage/MyTimePage.tsx
> Feature: my timeline tasks done functionality

- src/helpers/InboxProcessor.ts
- src/utils/index.ts
> [Sharing Goals] Fix: Convert incoming start and due values in date object 

- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.scss
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Update: Show subtext in goal actions | Patch: Non-editable view of shared goal tags

- src/components/GoalsComponents/ArchivedAccordion/ArchivedAccordion.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/service-worker/serviceWorkerRegistration.ts
> Feature: Notification Drawer in inbox

- src/App.tsx
- src/api/PubSubAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/helpers/InboxProcessor.ts
> fix: sublist archive drawer & collab not working

- cypress/integration/home-page.spec.ts
- index.html
- src/pages/LandingPage/LandingPage.tsx
"Better together" is a tagline that:
- is simpler and shorter - and thus easier to remember
- has a more ethical feel
- fits more of the ZinZen use cases / target markets
than "Realize dreams together"
> Change tagline

- src/App.tsx
- src/api/GoalsAPI/index.ts
- src/api/InboxAPI/index.ts
- src/components/GoalsComponents/DisplayChangesModal/IgnoreBtn.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/helpers/GoalProcessor.ts
- src/helpers/InboxProcessor.ts
- src/services/contact.service.ts
Resolves #1128 
Resolves #1135 
Resolves #1134
> New Updates: Goal Sharing & Collaboration 

- src/store/DarkModeState.ts
- src/store/ThemeState.ts
> Fix: check & update dark mode and theme values when app opens

- src/common/ConfirmationModal.tsx
- src/constants/myGoals.ts
Resolves #1176 
update context specific text to confirm dialog to make action more clear
> improve confirmation modal UX, closes #1176

- src/components/BottomNavbar/BottomNavbar.tsx
Resolves #1182
can you please verify this.
> issue fixed #1182

- src/common/Header/Header.tsx
Resolves #1184 
Before fix:
After fix:
> #1184 fix: Increased tap area for toggle

- src/common/Header/Header.tsx
Added blog link to dropdown menu. Solves issue #1187
> Solves #1187: added blog link to dropdown menu

- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.scss
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
- src/global.scss
- src/pages/InvitePage/InvitePage.tsx
> Update: Duration in Edit goal popup | Fix: budget period value getting reset

- src/App.tsx
- src/Interfaces/ICommon.ts
- src/common/SubHeader.tsx
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.scss
- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
- src/components/GoalsComponents/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/SuggestionModal/SuggestionModal.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/components/MyTimeComponents/Reschedule/Reschedule.scss
- src/components/MyTimeComponents/Reschedule/Reschedule.tsx
- src/global.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/pages/ShowFeelingsPage/ShowFeelings.scss
- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
- src/store/TaskState.ts
- src/store/index.ts
- src/utils/index.ts
> Feature: Reschedule Popup

- src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
Updated the code to change the color of the caret according to the theme of the goal
> update: caret's color changes dynamically 

- src/common/ConfirmationModal.tsx
Added label and id attributes to Form.Check component. This made the whole component clickable.
Resolves #1174
> update: increased checkbox's touch area. Solves #1174

- src/api/GCustomAPI/index.ts
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalSublistPage/GoalSublistPage.tsx
- src/components/GoalsComponents/GoalsList.tsx
- src/layouts/DragAndDrop.tsx
- src/models/GCustomItem.ts
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Feature: Drag and Drop Goals

- src/pages/FAQPage/FAQPage.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
- src/translations/de/translation.json
- src/translations/en/translation.json
- src/translations/es/translation.json
- src/translations/fr/translation.json
- src/translations/hi/translation.json
- src/translations/nl/translation.json
- src/translations/pt/translation.json
Made 3 commits: 
1. Solves #1181 : renamed archivedGoal and setArchivedGoal state variables to doneGoal and setDoneGoal.
2. Added translation for Continue button present in FAQPage.tsx
3. Fixed Continue button text and right arrow img alignment.
> Added: Translation of Continue Button on FAQ UI

- src/Interfaces/index.ts
- src/common/Header/Header.tsx
- src/hooks/useGlobalStore.tsx
> Patch: Change Theme supports native back button

- vite.config.ts
> Update: pwa now cache files like images, sounds and .wasm

- cypress/integration/inbox.spec.ts
- src/common/ColorPalette.tsx
- src/common/Header/Header.tsx
- src/components/BottomNavbar/BottomNavbar.tsx
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/hooks/useFeelingStore.tsx
- src/hooks/useGoalStore.tsx
> Patch: Minor updates and fix

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> fix: close popup one update or add goal is clicked

- src/components/GlobalAddBtn.tsx
> patch: when confirming theme change go back to prev state in history

- src/common/Header/Header.tsx
> added: install button in dropdown options

- src/App.tsx
- src/pages/InvestPage/InvestPage.scss
- src/pages/InvestPage/InvestPage.tsx
> Update: Users can access feedback page without finishing onboarding

- package-lock.json
- src/common/Header/Header.tsx
> [ BUG ] Fix: multiple install button in dropdown

- src/common/Backdrop.tsx
- src/components/BottomNavbar/BottomNavbar.tsx
> Update: Prevent other actions while user is changing theme 

- src/common/Loader.tsx
- src/components/GoalsComponents/ShareGoalModal/AddContactModal.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
Fix: Share with 1:1 not opening contact list
Fix: Loader not appearing on correct positioning in Add contact & Share goal modal
> UI Patches

- src/Interfaces/ISchedulerInputGoal.ts
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/helpers/MiniScheduler.ts
- src/hooks/useGoalStore.tsx
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/SchedulerUtils.ts
- src/utils/index.ts
fix: selected color changes when user open edit goal
> Feature: JS scheduler v2

- src/helpers/MiniScheduler.ts
- src/pages/MyTimePage/MyTimePage.tsx
Fix: don't fake next day in dev mode
> Fix: wrong order of dates scheduler output

- src/helpers/MiniScheduler.ts
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/SchedulerUtils.ts
Updates
- treat non-duration goal ( having duration defined children ) as clubbers and not generate their fillers 
- handle deadline of goals while putting them for scheduling on the respective day
> Patch: Scheduler v2 considers Due date while scheduling | Update: clubber check

- src/components/BottomNavbar/BottomNavbar.tsx
> PATCH: go back from where you came if you are going to same again

- src/components/GoalsComponents/GoalSublist/GoalHistory.tsx
> fix: Breadcrumb home icon, separator dark mode styling

- src/components/GlobalAddBtn.tsx
resolves #1291 
@tijlleenders @Tushar-4781
> fix: add feeling button

- src/common/ConfirmationModal.tsx
This resolves issue #1190 
Old Modal Screenshot 
New Modal Screenshot
> modal buttons position switched

- src/components/FeelingsComponents/AddFeeling.tsx
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/pages/ShowFeelingsPage/ShowFeelings.scss
> Patch: Back Btn navigation in My Journal page and popups

- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
- src/pages/ShowFeelingsPage/ShowFeelings.scss
This will close #1296 
Hey @Tushar-4781 & @tijlleenders I have added the code, mentioned in the feedback 
Listing layout
The note
> my journal feelings listings

- src/Interfaces/ISchedulerInputGoal.ts
- src/scheduler/ImpSlotManager.ts
- src/scheduler/TaskGenerator.ts
- src/scheduler/index.ts
- src/scheduler/miniScheduler.ts
- src/utils/SchedulerUtils.ts
> New Update: JS scheduler broken into chunks and functions

- src/pages/MyTimePage/MyTimePage.tsx
the **outputs** field changed to **tasks**
> patch: sync UI to output schema of scheduler

- src/App.tsx
> New Update: loading /donate path will now redirect to donate link

- src/components/GoalsComponents/MyGoal.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
- src/utils/patterns.ts
Resolves #1271 
Resolves #1272
> New Update: Title are scrollable and contain clickable urls

- src/Interfaces/ISchedulerInputGoal.ts
- src/api/TasksAPI/index.ts
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/MyTimeComponents/MyTimeline.tsx
- src/helpers/GoalProcessor.ts
- src/models/TaskItem.ts
- src/models/db.ts
- src/pages/MyTimePage/MyTimePage.tsx
- src/scheduler/ImpSlotManager.ts
- src/scheduler/TaskGenerator.ts
- src/scheduler/index.ts
- src/scheduler/miniScheduler.ts
Resolves #1280 
Resolves #1306 
Resolves #1307
> New Update: JS Scheduler handles the hours spent && Done Action Available for use

- src/utils/patterns.ts
> fix: urls without prefix not working

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> change default to 'Timings'

- src/scheduler/TaskGenerator.ts
> Fix: handle second half of the splitted goal while generating tasks

- src/utils/SchedulerUtils.ts
> Removed: "filler" text from parent goal

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
> Removed: Husky dep

- src/helpers/GoalLocStateHandler.tsx
- src/hooks/useGoalStore.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> Fix: Navigation between goal and its other components  

- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/scheduler/freeSlotsManager.ts
- src/scheduler/miniScheduler.ts
Resolves #1277 
Resolves #1333
> Patch: Scheduler gives free slots in scheduled tasks

- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
> Update: color bands with rounded corner

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/scheduler/TaskGenerator.ts
Resolves #1347 
Resolves #1349
> Patch: Scheduler and Goal Configuration clash

- src/Interfaces/index.ts
- src/components/GoalsComponents/MyGoal.tsx
- src/components/MyTimeComponents/MyTimeline.scss
- src/components/MyTimeComponents/MyTimeline.tsx
- src/pages/MyGoalsPage/MyGoalsPage.tsx
> New Update: allow navigation from task to goal upto n level

- src/pages/MyTimePage/MyTimePage.tsx
Hey, I fixed the issue. Your app is cool. Let me know if there is anything else I can do
> fixed hours issue

- src/Interfaces/IPages.ts
- src/Interfaces/Task.ts
- src/components/MyTimeComponents/ColorBands.tsx
- src/components/MyTimeComponents/MyTimeline.tsx
- src/components/MyTimeComponents/index.scss
- src/helpers/MyTimeHelper.ts
- src/pages/MyTimePage/MyTimePage.tsx
> Feature: Progress of the day on My Time Page

- src/components/MyTimeComponents/MyTimeline.tsx
- src/components/MyTimeComponents/index.scss
Resolves #1378
I've made strike through slight thick so that it could be easily visible when light shades of colours were used.
> Give strike through of task the goal colour

- src/App.tsx
- src/__tests__/rawDBScript.js
- src/api/TasksAPI/index.ts
- src/utils/index.ts
> Update: Sync the previous day(s) data before generating new schedule of the day 

- src/api/TasksAPI/index.ts
- src/components/MyTimeComponents/MyTimeline.tsx
- src/helpers/MyTimeHelper.ts
- src/hooks/useScheduler.tsx
- src/models/TaskItem.ts
- src/models/db.ts
> Update: tasks marked Done or Forget are in sync in the coming days

- src/pages/MyTimePage/MyTimePage.tsx
> Resolves #1373

- src/App.tsx
Cause: Donate path was not present in exception routes variable
Resolves #1165
> Patch: allow user to access donate page without onboarding as well

- src/common/ConfirmationModal.tsx
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
> Requested Changes in config Goal and actions

- src/components/GoalsComponents/MyGoal.tsx
This change resolves #1413 by adding conditional rendering for goal start date.
> Don't show start when no due and not in future #1413

- src/components/GoalsComponents/MyGoal.tsx
- src/pages/MyGoalsPage/MyGoalsPage.scss
> Fix: title and circle alignment

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/customize.scss
- src/global.scss
> Fix: UI colors

- src/common/ConfirmationModal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
> fix: Share popup closing after making choice in confirmation popup

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> Fixes #1433 Default values added to hours of the day

- src/components/MyTimeComponents/MyTimeline.tsx
- src/components/MyTimeComponents/index.scss
> Update: allow navigation from completed task to its goal

- src/components/BackupRestoreModal.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/models/db.ts
- src/pages/MyGoalsPage/MyGoalsPage.scss
> Update: Sync the version of backup data to the current version of db

- src/common/Header/Header.scss
- src/common/Header/Header.tsx
> chore: made icon align with goal circles

- src/pages/GoalsPage/GoalsPage.scss
Resolves #1461 
Placed the css into Wrong class
> fix: alignment of pencil in goals dropdown

- src/components/GoalsComponents/GoalSublist/GoalHistory.tsx
Resolves #1439 
Resolves #1463 
Resolves #1464
> update: breacrumb background and navigation fix

- src/components/Header/Header.tsx
> update: clicking on title of my goals takes you back to root goals

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
I have renamed  Share1:1 to Share privately in the Share goals  #1469 
Resolves #1469
> Renamed the Share 1:1 into Share privately

- README.md
- documentation/Readme.md
Resolves  #1476
Simplified wording, fixed link and punctuation.
> Fix/broken-link in README.md #1476

- src/components/GoalsComponents/GoalSublist/GoalHistory.tsx
> style(breadcrumb): update borderRadius and height

- src/components/HeaderDashboard/MainHeaderDashboard.tsx
- src/hooks/useGoalStore.tsx
> fix: correct random index generation

- src/components/Header/Header.scss
- src/components/Header/Header.tsx
> fix: logo and MyGoal aligment

- src/components/GoalsComponents/MyGoal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
> add: goal menu subtext

- src/components/GoalsComponents/GoalSublist/GoalHistory.tsx
- src/global.scss
> refactor: replace and align goalHistory home icon

- src/pages/MyTimePage/MyTimePage.tsx
- src/store/index.ts
> Fixed calender position issue when switching in sub menu 

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
Resolves #1443 
All the underlined field in modal, will have this feature
> Auto reduce max duration to 99 issue fix

- README.md
> add ELI5 part

- .github/workflows/playwright.yml
- .gitignore
- package-lock.json
- package.json
- playwright.config.ts
- playwright/example.spec.ts
> add: playwright env

- src/layouts/BottomNavLayout.tsx
> refactor: bottom navbar border radius

- src/Interfaces/index.ts
- src/api/InboxAPI/index.ts
- src/api/SharedWMAPI/index.ts
- src/components/BackupRestoreModal.tsx
- src/components/GoalsComponents/DisplayChangesModal/AcceptBtn.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/DisplayChangesModal/Header.tsx
- src/components/GoalsComponents/DisplayChangesModal/IgnoreBtn.tsx
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
- src/global.scss
- src/helpers/GoalLocStateHandler.tsx
- src/helpers/GoalProcessor.ts
- src/helpers/InboxProcessor.ts
- src/helpers/PartnerController.ts
- src/models/GoalItem.ts
- src/models/db.ts
- src/override.scss
- src/pages/GoalsPage/MyGoals.tsx
- src/store/GoalsState.ts
- src/utils/SchedulerUtils.ts
- src/utils/index.ts
This PR is not tested fully but achieves the following:
1. Partner can share suggestion
2. Multiple Participants can receive updates 
3. One user can receive changes but cannot propagate to other participants
Resolves #1491 
Resolves #1551
> Restored: Suggestion and Collaboration features

- documentation/ADR/001-wasm-scheduler.md
Use a stateless WASM scheduler module/function written in Rust.
> ADR-001 WASM scheduler in Rust

- src/components/GoalsComponents/MyGoal.tsx
- src/pages/GoalsPage/GoalsPage.scss
> edit: Update goal circle icon representation

- src/components/GoalsComponents/MyGoal.tsx
> edit: decrease outer cicle's inner glow

- src/components/GoalsComponents/MyGoal.tsx
> add: dashed border to budget

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> feat: confirm edit goal by pressing enter

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/MyGoal.tsx
resolves #1571 
resolves #1572 
@tijlleenders please review the PR and I also think we need to change starter goal's tags
> modified update goal tags and frontend goal description based on goal type

- src/components/GoalsComponents/GoalsList.tsx
> fix: drag event not working

- src/components/GoalsComponents/MyGoal.tsx
- src/utils/index.ts
> add weekly hours subtext for budgets

- src/api/InboxAPI/index.ts
- src/components/GoalsComponents/DisplayChangesModal/AcceptBtn.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
- src/helpers/BatchPublisher.ts
- src/helpers/GoalController.ts
- src/helpers/InboxProcessor.ts
- src/helpers/PubSubController.ts
Resolves #1519 
Resolves #1590 
Resolves #1559
>  Enhancement: Sending the modifications to other ppts in sharing and collaboration.

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
resolves #1573 
@tijlleenders is this what you expected?
> edit: expand set budget accordian by default

- src/components/GoalsComponents/MyGoal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
- src/pages/GoalsPage/GoalsPage.scss
> refactor: replace action text with three dots

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/GoalConfigModal/CustomDatePicker.tsx
- src/components/GoalsComponents/MyGoal.tsx
- src/translations/en/translation.json
- src/translations/nl/translation.json
- src/utils/index.ts
> add due date field

- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
> edit: title click leads to edit goal screen

- src/components/GoalsComponents/MyGoalActions/ActionDiv.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.scss
> Simplify edit modal

- src/Interfaces/ICommon.ts
- src/common/Accordion.tsx
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> replace sumary expanded menu

- src/common/Search.tsx
- src/components/Header/Header.scss
- src/components/Header/HeaderBtn.tsx
- src/components/Header/Settings.tsx
> edit: increase tap area of header buttons

- src/services/contact.service.ts
- src/services/goal.service.ts
Updates lambda endpoints due to backend-driven changes.
> update lambda endpoints

- cypress.config.ts
- src/components/GlobalAddBtn.tsx
- src/components/GoalsComponents/MyGoal.tsx
> update cypress tests 

- documentation/technical/PRGuide.md
- documentation/technical/Readme.md
- documentation/technical/Setup.md
- documentation/technical/conventions/Readme.md
- documentation/technical/conventions/code.md
- documentation/technical/conventions/git.md
resolves #250 
@tijlleenders @Tushar-4781, feel free to add more tasks related to contributions if needed
> add contributing instructions

- src/pages/GoalsPage/MyGoals.tsx
> keep zinzen text logo visible

- package-lock.json
- src/utils/index.ts
Resolves #1630 
For this issue (#1630), I made changes in the file **index.ts**. I changed the color to more darker and better color shade.
> Replaced the current yellow color with the yellow that has better contrast in light theme 

- src/constants/starterGoals.ts
- src/helpers/GoalProcessor.ts
> dynamic array length for random color selection

- src/components/GlobalAddBtn.tsx
- src/components/index.scss
> goal add button positioning

- src/pages/GoalsPage/MyGoals.tsx
Tip @HadassaAvimor : adding 'Resolves #1654 ' to PR description will auto-close the issue on merge ;)
> resize logo in Goals Page

- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
> Consistent font size in edit modal

- src/common/ConfirmationModal.tsx
@tijlleenders, Now "cancel" button in both delete and done confirmation modal working properly.
Resolves #1669
> #1669 Issue: "cancel" button issue solved

- src/components/Header/Header.scss
- src/components/Header/Header.tsx
- src/store/index.ts
> add flip animation to ZZ logo when switching partner mode

- src/components/GoalsComponents/MyGoal.tsx
> fix goal action not opening for sub-goals in partner mode

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
Resolves #1676
Hello @tijlleenders, solved that text warning. can you please check this once?
> #1676 Issue: Solved text warning

- src/helpers/MyTimeHelper.ts
> send list of goals to scehduler instead of map

- src/Interfaces/IScheduler.ts
- src/helpers/MyTimeHelper.ts
- src/pages/MyTimePage/MyTimePage.tsx
> refactor: input budget field to include min/max per day and week

- src/components/LanguageChoice/LanguagesList.tsx
> Issue #1680 - Show language alphabetically expect first

- src/pages/FAQPage/FAQPage.tsx
- src/pages/LandingPage/LandingPage.tsx
Resolve #1699
@tijlleenders can you please check this?
> #1699 Issue: Added tagline on second onboarding screen

- src/translations/en/translation.json
- src/translations/fr/translation.json
- src/utils/index.ts
> Issue #1705 - Showing overdue days for goals

- src/pages/GoalsPage/MyGoals.tsx
> Issue #1706 - Centering the ZinZen text logo

- src/App.tsx
> Issue #1684 - Making toast message disappear when clicking on screen

- src/components/GoalsComponents/MyGoal/GoalTitle.tsx
@tijlleenders , Can you please check this?
> #1697 Issue: Removed space in front of a URL

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.scss
- src/components/GoalsComponents/Participants.tsx
- src/override.scss
> add hint toggle in config modal

- src/constants/starterGoals.ts
> fix: removed id from starter goals array

- src/common/ColorPalette.tsx
- src/common/ColorPicker.tsx
- src/common/index.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/global.scss
resolves #1483 
- Moved colorpicker to top of config modal
- Revamped colorpicker component. Added a compact, scrollable color palette popup to ColorPicker for improved user interface
> better color selector with popup

- documentation/ADR/003-use-react-framework.md
Add ADR from 2022-01 to use React framework.
> add ADR 003 Use react framework

- README.md
> removed duplication in readme

- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
> Included edit functionality in journal notes

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> add: hint toggle

- documentation/ADR/004-use-next-framework.md
Update ADR NextJS with latest insights.
> update ADR NextJS with latest insights

- documentation/ADR/005-use-RESTful-API.md
Formalizing decision made this year not to move to WebSockets.
> Add ADR RESTful API

- src/Interfaces/ILanguage.ts
- src/components/LanguageChoice/LanguagesList.tsx
- src/pages/LandingPage/LandingPage.tsx
> Issue#1731 - Clearer layout for landing page language choice

- src/components/Header/Header.scss
- src/components/Header/Settings.tsx
- src/components/Sidebar.tsx
> edit menu font size and dropdown size

- src/constants/starterGoals.ts
> move sleep starter goal to daily habits

- src/Interfaces/IScheduler.ts
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/constants/starterGoals.ts
- src/helpers/GoalProcessor.ts
- src/helpers/MyTimeHelper.ts
- src/models/GoalItem.ts
> update goal item configuration and processing to handle update scheduler

- src/Interfaces/IScheduler.ts
- src/helpers/MyTimeHelper.ts
> make min_duration minDuration

- src/components/GoalsComponents/MyGoal/GoalSummary/BudgetTimeSummary.tsx
- src/components/GoalsComponents/MyGoal/GoalSummary/GoalSummary.tsx
- src/components/GoalsComponents/MyGoal/GoalSummary/useSublistSummary.ts
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
> fix e.timebudget is null error when clicking goal with due-date

- .github/workflows/cypress.yml
Reverts tijlleenders/ZinZen#1776
> Revert "patch: removing the check from cypress.yml to allow tests to run "

- playwright/goal-sharing-feature.spec.ts
- playwright/lib/testUtils.ts
> fix goal-sharing-feature test

- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
- src/components/MyTimeComponents/MyTimeline/TaskOptions.tsx
- src/components/MyTimeComponents/MyTimeline/index.scss
Resolves #1765
Modified the title functionality to allow toggling the Task open and close as requested.
Added a new button within the action buttons to enable users to navigate directly to the associated Goal page.
Please review the changes and provide feedback. Let me know if any adjustments are needed. I'm open to making further modifications as required.
> Toggle Task Open/Close and Add Goal Navigation Button

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/GoalSublist/GoalHistory.tsx
- src/components/GoalsComponents/MyGoal/GoalSummary/GoalSummary.tsx
- src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
- src/components/Header/Header.scss
- src/components/Header/Settings.tsx
- src/components/MyTimeComponents/Focus.tsx/Focus.tsx
- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
- src/helpers/MyTimeHelper.ts
> persist goal title translation across app

- README.md
Minor update to explanation.
Simplification of language.
> small addition to explanation

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
fix issue #1786 
Resolves #1786
> fix: wording of sharing text

- src/components/BottomNavbar/BottomNavbar.scss
- src/components/index.scss
This PR fix this issue https://github.com/tijlleenders/ZinZen/issues/1796
> Fix: Image aligned in the center inside button

- src/components/GoalsComponents/MyGoal/GoalSummary/GoalDurationSummary.tsx
- src/utils/index.ts
Reverts tijlleenders/ZinZen#1799
This PR resulted in a broken dev.
Reproduce:  
- Launch this build  
- Go to my goals 
- try to navigate one layer down into daily goals
https://react.dev/errors/310?invariant=310
> Revert "only add translation to word part in formatSingularPlural function"

- src/pages/ShowFeelingsPage/ShowFeelingsPage.tsx
- src/utils/index.ts
> edit: get date input in getJustDate util function

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> allow users to set 0 as minimum budget value

- src/components/GoalsComponents/MyGoal/GoalSummary/GoalDurationSummary.tsx
- src/translations/de/translation.json
- src/translations/en/translation.json
- src/translations/es/translation.json
- src/translations/fr/translation.json
- src/translations/gt/translation.json
- src/translations/hi/translation.json
- src/translations/mr/translation.json
- src/translations/nl/translation.json
- src/translations/pt/translation.json
- src/utils/index.ts
> handle localized plural form of hour correctly 

- src/components/MyTimeComponents/MyTimeline/index.scss
make font-weight consistent so it's easier on eyes
> make font-weight consistent so it's easier on eyes

- cypress/integration/bottom-nav.spec.ts
- src/hooks/useApp.tsx
- src/pages/FAQPage/FAQPage.scss
- src/pages/FAQPage/FAQPage.tsx
- src/pages/LandingPage/LandingPage.scss
- src/pages/LandingPage/LandingPage.tsx
- src/store/DarkModeState.ts
resolves #1820 
- modified getDarkModeValue() to return "on" by default
- modified useApp() hook to set "darkMode" key in localStorage to "on"
> edit: set dark theme as default for new users

- src/components/GoalsComponents/MyGoal/GoalDropdown.tsx
- src/components/GoalsComponents/MyGoal/MyGoal.tsx
- src/components/Header/Header.scss
- src/pages/GoalsPage/GoalsPage.scss
Resolves #1822 
We can still improve some alignments, removing percentages and treating them better with flexbox.
But the alignment has already been improved.
> #1822 fix some alignments

- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
closes #1811 
Now clicking on a done task it will toggle the task extra info. other way to say it will behave like a accordion.
@tijlleenders
> fix: when click on a task title toggle the extra info

- src/components/BottomNavbar/BottomNavbar.scss
- src/components/FeelingsComponents/AddFeeling.scss
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
- src/components/MyTimeComponents/MyTimeline/index.scss
- src/components/index.scss
- src/customize.scss
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx
> Make clickable elements cursor pointer

- src/helpers/MyTimeHelper.ts
> dont send filter key to scheduler if after and before are null

- src/pages/FAQPage/FAQPage.tsx
- src/pages/LandingPage/LandingPage.scss
- src/pages/LandingPage/LandingPage.tsx
> edit font-size of lang choice buttons

- src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
Resolves #1741 
I have removed the "Share goals" text and only made the "Share in Public group" text visible when the person is trying to share it in group.
> Fix extra text in share goal model

- src/components/GoalsComponents/MyGoal/MyGoal.tsx
- src/pages/GoalsPage/GoalsPage.scss
Pull Request: Enhancing User Experience with Temporary Visual Highlight
Description:
Resolves #1354 
This pull request addresses the need for improved user experience when navigating from the MyTime page to the GoalsPage. To facilitate easier goal identification, I have implemented a temporary visual highlight effect on the selected goal.
> Add visual glow to navigated goal

- src/api/ContactsAPI/index.ts
- src/components/GoalsComponents/Participants.tsx
- src/components/GoalsComponents/ShareGoalModal/AddContactModal.tsx
- src/hooks/useGetRelationshipStatus.ts
- src/models/ContactItem.ts
- src/models/db.ts
- src/pages/GoalsPage/InvitationStatus.tsx
- src/pages/GoalsPage/PartnerGoals.tsx
- src/pages/InvitePage/InvitePage.tsx
> explain empty partner page

- .github/workflows/Jest.yml
- .github/workflows/cypress.yml
- .github/workflows/lint.yml
- .github/workflows/playwright.yml
- .github/workflows/tslint.yml
> update playwright workflow to support node 20

- README.md
add Explain It Like I'm 5 for philanthropists.
> add philanthropist ELI5

- README.md
add OS/kernel dev ELI5 in README.md
> add OS/kernel dev ELI5

- vite.config.ts
update manifest for open-store.io
> update manifest for open-store.io

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> fix between slider not working properly

- src/components/BackupRestoreModal.tsx
- src/models/db.ts
- src/models/dexie.ts
resolves #1913 
@tijlleenders check if error is fixed
> fix "completedTodayTimings" is undefined

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/hooks/useSublistSummary.ts
> fix: stale values returned by useSublistSummary hook

- pkg/scheduler.d.ts
- src/components/MyTimeComponents/SchedulerErrorModal.tsx
- src/helpers/MyTimeHelper.ts
- src/hooks/useScheduler.tsx
- src/store/SchedulerErrorState.ts
> regularly show scheduler error modal and handle cached schedule storage on scheduler crash 

- src/components/GoalsComponents/GoalSublist/GoalSublist.scss
> auto capitilize goal title fix

- src/api/TrashAPI/index.ts
- src/hooks/useApp.tsx
> feat: implement automatic trash cleanup

- src/common/Backdrop.tsx
- src/components/GlobalAddBtn.tsx
- src/hooks/useLongPress.tsx
> add goal quicker

- src/constants/starterGoals.ts
> fix: edit budget bug for starter goals

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/MyGoal/MyGoal.tsx
> Breadcrumb only shows latest level down

- src/api/TasksAPI/index.ts
- src/helpers/MyTimeHelper.ts
> adjust not on blocks for scheduler input

- src/components/GoalsComponents/GoalSublist/GoalSublist.tsx
> goalitem summary not visible in subgoal component

- src/components/BottomNavbar/BottomNavbar.tsx
> subgoalhistory bug

- src/components/BottomNavbar/BottomNavbar.tsx
- src/components/GlobalAddBtn.tsx
- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/index.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/react-app-env.t.ts
> add goal from my time page

- src/components/GlobalAddBtn.tsx
> open new goal addition modal with enter and plus button press

- src/api/TasksAPI/index.ts
- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
- src/components/MyTimeComponents/NotNow/NotNowModal.tsx
- src/helpers/MyTimeHelper.ts
- src/models/TaskItem.ts
- src/models/dexie.ts
- src/utils/rawDBScript.js
> remember what is skipped for the current day

- src/hooks/useGoalActions.tsx
- src/utils/index.ts
> show goal update confirmation

- src/api/SharedWMAPI/index.ts
- src/api/TrashAPI/index.ts
- src/assets/CopyIcon.tsx
- src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
- src/components/GoalsComponents/GoalSublist/GoalSublist.tsx
- src/components/GoalsComponents/MyGoal/MyGoal.tsx
- src/components/GoalsComponents/MyGoal/components/GoalDropdown.tsx
- src/components/GoalsComponents/MyGoal/components/GoalTitle.tsx
- src/hooks/useGoalActions.tsx
- src/pages/GoalsPage/MyGoals.tsx
- src/pages/GoalsPage/PartnerGoals.tsx
- src/pages/GoalsPage/components/ArchivedGoals.tsx
- src/pages/GoalsPage/components/DeletedGoals.tsx
- src/utils/patterns.ts
> fix bugs related to deleted and archived goal items

- src/common/index.scss
> fix: color picker in config goal modal not clickable

- src/App.tsx
> fix: cant add goal in mytimepage as app errors out

- src/pages/FeedbackPage/FeedbackPage.tsx
- src/pages/FeedbackPage/feedbackpage.scss
Resolves #2030 
Changed the color of stars in Dark and Light mode
Screenshots
> fix: Highlight extra stars #2030

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- documentation/technical/PRGuide.md
- documentation/technical/Setup.md
- documentation/technical/conventions/Readme.md
- documentation/technical/conventions/code.md
- documentation/technical/conventions/git.md
- pkg/README.md
- src/api/GoalsAPI/index.ts
- src/components/GoalsComponents/GoalsList.tsx
- src/components/GoalsComponents/MyGoal/components/GoalDropdown.tsx
- src/components/MyTimeComponents/ColorBands.tsx
- src/components/MyTimeComponents/MyTimeline/index.scss
- src/override.scss
- src/pages/FeedbackPage/feedbackpage.scss
- src/pages/MyTimePage/MyTimePage.scss
- src/pages/MyTimePage/MyTimePage.tsx
- src/utils/patterns.ts
> fit:removed % Done bar

- src/components/GoalsComponents/GoalSublist/components/GoalHistory.tsx
- src/hooks/useGoalSelection.ts
- src/hooks/useKeyPress.ts
the goal modal now opens with spacebar key, a similar action which could be performed by clicking the goal as well
fixes #2053 
Screenshot:
> feat: open goal modal with spacebar key

- src/common/ZModal.tsx
> Add escape key event listener to call onCancel function on modals

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/components/GoalsComponents/GoalConfigModal/components/AutoComplete.scss
- src/components/GoalsComponents/GoalConfigModal/components/AutoComplete.tsx
> Enable clicks on entire title area for suggestions

- src/pages/GoalsPage/GoalsPage.scss
> delete duplicate code in GoalsPage.scss

- src/hooks/useApp.tsx
- src/pages/GoalsPage/PartnerGoals.tsx
Fixed issue #2075 which cause the share list to not get updated after a refresh.
now share list keeps updating in background.
hope it helps
> Fixed Issue #2075 share list update

- src/components/GoalsComponents/MyGoal/MyGoal.tsx
- src/components/GoalsComponents/MyGoal/components/GoalTitle.tsx
- src/pages/GoalsPage/GoalsPage.scss
> code snippet not copying when url is present

- src/App.tsx
> feat: destroy toast when clicked outside it

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
> Remove Dots at End

- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
> fix: task not being created in db for postpone action

- src/Interfaces/IScheduler.ts
- src/api/TasksAPI/index.ts
- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
- src/helpers/MyTimeHelper.ts
- src/models/TaskItem.ts
- src/models/db.ts
- src/models/dexie.ts
> remove unused properties

- src/__tests__/TrashApi/index.test.ts
- src/api/TrashAPI/index.ts
> fix: cleanupTrash not working

- .eslintrc.json
resolves #2117 
added eslint rule to enforce a max cyclomatic complexity threshold
```json
"complexity": "warn",
```
> add complexity eslint rule

- src/components/GoalsComponents/MyGoal/GoalTitleHandlers.tsx
- src/components/GoalsComponents/MyGoal/MyGoal.tsx
- src/components/GoalsComponents/MyGoal/components/GoalTitle.tsx
> only open link on new tab when exactly clicked on it

- src/Interfaces/IScheduler.ts
- src/api/SchedulerOutputCache/index.ts
- src/helpers/MyTimeHelper.ts
- src/hooks/useScheduler.tsx
> fix schedule not cached properly

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/hooks/useApp.tsx
- src/hooks/useScheduler.tsx
> use react query to get scheduled task

- src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
- src/controllers/GoalController.ts
> fix: prevent goal creation UI delay caused by waiting for network updates

- src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
- src/components/MyTimeComponents/MyTimeline/TaskOptions.tsx
> complete task immediately
