js/helpers.js

Was mistakenly assuming the collection was not clearing since console.log showed values upon expanding.
The log showed length of 0 so that was confusing. Browser console does not remember historic state for expansion!

fix: console shows current value upon expanding

---

src/components/myfeelingspage/FeelingSad.js

Change `r1eact-i18n` to `react-i18n` that was causing issues with the deployment

Fix typo in `react-i18n` import

---

cypress/integration/home-page.test.js

The cypress test was failing in the latest commits, this was because of adding translations to the landing page. 
(The landing page detects the browser's default language and if it is among the translations then the page gets translated into that language, else English is set as the fallback language for now)

Modify cypress test

---

src/components/404page/NotFoundPage.jsx
src/components/dashboard/HeaderDashboard.jsx
src/components/dashboard/UserChoiceDashboard.jsx
src/components/landingpage/Header.jsx
src/components/languagechoices/LangItem.jsx
src/components/themechoicepage/ThemesChoice.jsx

Resolves #248 
This was such a stupid fix. I searched around a lot for what could be the cause of these reloads since the very reason for using ReactJS is to have SPA functionality and so the app shouldn't reload on route changes. Then I looked into the HMR of ViteJS and tried a few things but couldn't find any resources about it since there is no way this should happen at all.
Finally, when going through the code one last time I saw a wild `window.location.reload(false);` and then on doing a global search found out that there were around 10 of these at all the places where you would click somewhere to change the page. Removing them fixed the problem, felt so dumb after finding that out 😆

Remove page reloads from the code

---

.github/workflows/cypress.yml
.github/workflows/lint.yml
.github/workflows/tslint.yml

As can be seen in PR #311 the GitHub Actions don't get triggered.
This is because the PR comes from a forked repo  
=> not pushing to the ZinZen repo  
=> not triggering 'push' event on ZinZen repo
=> not triggering GitHub Actions.
I added a trigger for pull_request: [opened, edited, ready_for_review]

added Pull Request from fork actions triggers

---

src/pages/MyTimePage/MyTimePage.scss
src/pages/MyTimePage/MyTimePage.tsx
src/utils/index.ts

Resolves #477
Resolves #481 
Resolves #490 
Upgrade in solution for #476
To make review easy ( for #481 ) I've made a commit with a message **checkpoint: Preview**. Consider the vercel deployment preview link after this commit to compare and differentiate with the last deployment link ( **checkpoint: Final Preview** )
1. For testing purpose, i have created the function for populating dummy tasks. Creating a collection and set of apis for MyTimePage has to be discussed so till then to keep the code complexity minimum i m using the goals as tasks.
2. The "Unplaned" word represents the user have no tasks in that particular duration i.e. **unplanned time**. Rest other dummy names represent the task name like "Gym" -> "Go to Gym" 
3. Reason for introducing the point 2 is to have a record of …

Integration in MyTimePage: Duration + Width Normalization + DummyTasks (with Timestamp)

---

src/__tests__/GoalParser.test.ts
src/api/GoalsAPI/index.ts
src/components/GoalsComponents/AddGoal/AddGoalForm.scss
src/components/GoalsComponents/AddGoal/AddGoalForm.tsx
src/components/GoalsComponents/UpdateGoal/UpdateGoalForm.tsx
src/models/GoalItem.ts

Resolves #576 
The aim of this PR was to modify the goal parser and introduce a new property **link** in Goals schema which will be used to store the link. Earlier URL was part of the title.
The URL that which user enters in the input field will be stored separately. Which means it won't be visible with the goal title.
Instead of the whole link **"URL"** text will appear at the end of the goal title on the MyGoals page and it will be clickable. We have a separate issue for this functionality ( #513 ) and will be resolved a new PR.

Updated: Goal parser | Added: Link property in GoalItem Interface

---

src/pages/ThemeChoice/ThemeChoice.tsx
src/translations/de/translation.json
src/translations/en/translation.json
src/translations/es/translation.json
src/translations/fr/translation.json
src/translations/hi/translation.json
src/translations/nl/translation.json
src/translations/pt/translation.json

Hi Tushar, the bug that revolved around "Light colors" and "Dark colors" text translation on Theme Choice page has been resolved.
To resolve it, I first read the complete details about the bug. Then, as mentioned that the text was hard coded, so I concluded that this was not a bug but just that maybe the translator function wasn't yet implemented on the page.
I looked on the pages where the translation was working fine, so I just read more about it on the i18 documentation page. And accordingly translated both the strings in the necessary languages and copied those translations over the translation pages that are already present. 
After this, I just called the translator function with these strings as parameters in them. This worked well and it was translating it for all languages …

bug for light and dark color text translations resolved

---

src/common/Accordion.tsx

- Added the `accordion` to make sure only one Panel is visible at a time.
This closes #1192

fix: [#1192] Added accordion prop to Collapse

---

README.md

Just to remind people like me to update nodejs on systems where the older version <18 is the default.

add nodejs reminder

---

README.md

Add references between the Readmes of the main ZinZen repository and the ZinZen-scheduler repository to increase ease of navigation for visitors.

Reference ZinZen-scheduler repository in README.md

---

src/components/BottomNavbar/BottomNavbar.tsx

PR to close #1381 
- Import `{goalsHistory}`
- Add an `if else` statement to go back to goal hierarchy root
In the else statement I'm checking if goalsHistory length is not 0, otherwise clicking the Goals button reloads the entire page. It feels a bit strange but I'm not too familiar with Recoil.js. If there's a way around it or a better way to do it, I don't see it at the moment. If there isn't then good :)

Navigate to goal hierarchy root with Goals button

---

src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx

Resolves #1362 
I have removed expanded icon button from title and added besides the "**Create Goal**" button , and named it "**Options**" with expanded icon.
The options button **won't show up until duration is added to create a goal**. I tried to keep the options button disabled until  the duration is not added, but the disabled button color is same as active button color which can create confusion. 
Settings section gets auto closed if the duration is removed.
Following are the screenshots.
Old UI
Options button won't show until duration is added.
Options button visible when duration is added.

options btn added with icon

---

src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx

Resolves #1360 
Hi @Tushar-4781 & @tijlleenders 
This issue has been fixed. 
If input in decimal, it will be rounded off to the nearest whole number, with minimum value 1.
@tijlleenders, for the case of "0,5",where you mentioned that Dutch people use **comma** instead of **period**, this condition is already been handled, since the input type is set as **number**, it wont allow them to insert comma, while entering in hours.

Create goal input hours fix

---

documentation/ADR/000-template.md
documentation/technical/Readme.md

Kobe suggested we do this for the ZinZen-scheduler, and I think it's a good idea for this repo too.  
From my work experience this helps get new people up-to-speed on the core design decisions, and also helps avoid having the same discussion twice.

add ADRs to documentation

---

src/components/MyTimeComponents/index.scss
src/pages/GoalsPage/GoalsPage.scss

refactor: remove goals border bottom

---

src/components/GoalsComponents/GoalsList.tsx
src/components/GoalsComponents/MyGoal.tsx

Fixes issue #1553
The problem was with parsing URLs:
The following code
```
Number(ele.split("-")[1]);
```
returned NaN if there was anything other than digits after "-".
```
Number('zURL-5)'.split("-")[1]); // NaN since "5)" is not a number.
```
I used `String.matchAll` to get all URLs in the string (including edge cases like `(zURL-1)(zURL-2)`) and replace each one with a span.
Also added keys for react fragments in `GoalsList.tsx`: since they spammed in the console a lot :)

Fix for #1553 Url in parenthesis

---

documentation/technical/Readme.md

This PR updates the technical docs to include instructions for running the development server with the `npm run dev -- --host` command. This allows users to access the local server on mobile devices.

update docs to include command to access localhost on mobile devices

---

CONTRIBUTING.md
documentation/technical/Readme.md

Added a branching convention to the tech docs.  
This will help us navigate branches, stay out of each others way, and keep stale branches from becoming a thing.

add branching convention to tech docs

---

src/api/ContactsAPI/index.ts
src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
src/hooks/useApp.tsx
src/models/ContactItem.ts
src/models/db.ts

Resolves #1709  
PR Doc: 
1. Upon adding a contact, the goal ID will be saved in the "goalsToBeShared" field within the contacts collection.
2. Once a confirmation message is received indicating the acceptance of the invitation by the second person, a trigger will be activated.
3. The trigger will facilitate the sharing of all goals stored in the "goalsToBeShared" field.

Feature: mechanism for goals to be shared after invite get accepted 

---

src/Interfaces/ICommon.ts
src/common/ConfirmationModal.tsx
src/common/ZModal.tsx
src/components/BackupRestoreModal.tsx
src/components/FeelingsComponents/AddFeeling.tsx
src/components/GoalsComponents/DisplayChangesModal/DisplayChangesModal.tsx
src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
src/components/GoalsComponents/MyGoalActions/MyGoalActions.tsx
src/components/GoalsComponents/Participants.tsx
src/components/GoalsComponents/ShareGoalModal/AddContactModal.tsx
src/components/GoalsComponents/ShareGoalModal/ShareGoalModal.tsx
src/components/LanguageChangeModal/LanguageChangeModal.tsx
src/components/MyTimeComponents/Reschedule/Reschedule.tsx
src/pages/ShowFeelingsPage/ShowFeelingTemplate.tsx

This pull request introduces the `ZModal` component, which abstracts common props used in our existing antd modal.
- **Common Property Abstraction**: Centralizes shared modal properties to reduce redundancy.
- **Type-Based Customization**: Utilizes a `type` prop for applying distinct styles (can also be used for distinct behaviour), enhancing code clarity.
- **Easy Maintainability**: Simplifies updates and modifications to modal behaviour and appearance, ensuring changes are centralized and consistent.

refactor: introducing generic Custom ZModal for reduced redundancy and enhanced maintainability

---

.github/workflows/cypress.yml

This PR makes an attempt to fix the problem of tests not running in the PR(s) coming from forked repo(s)

patch: removing the check from cypress.yml to allow tests to run 

---

src/constants/starterGoals.ts

The starter goals were not realistic.  
You can't have 1 hour minimum per day on weekdays - and at the same time have a maximum of 4 per week.  
This PR fixes this.  
I've logged a separate issue #1788  as 0 is not allowed in the budget edit screen yet.

make start goals budget realistic

---

src/components/MyTimeComponents/MyTimeline/index.scss

Resolves #1764 
Toggled the thickness of the MyTime GoalTiming component and MyTime TaskOptions as requested. 
Please review the changes and let me know if any adjustments are to be made.

Swap font weight of goal timing and options

---

src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx

As detailed in [Issue #1809](https://github.com/tijlleenders/ZinZen/issues/1809), the problem appears to be related to the budget variation of the goal feature in our application. Specifically, the issue involves the inability to save and close the budget modal when pressing the Enter key, particularly when using a desktop browser.
While the original issue did not explicitly specify that the problem was confined to the budget variation, my investigation led me to this conclusion, and the implemented solution is focused on addressing this aspect.
To resolve this, I wrapped the contents of the modal in a form that allowed me to reduce redundancy by utilizing onSubmit to allow the goal to be saved by using enter.

[Issue #1809] || Allow 'enter' on keyboard for saving input on browser edit screen

---

src/components/Header/Header.tsx

Description of the Original Issue
As detailed in https://github.com/tijlleenders/ZinZen/issues/1531, the problem appears to be related to the quick toggle feature to switch between dark and light modes. The Icon would disappear depending on what time it was, in the case of the example shown it was when the nighttime logic was active, as I tested it the nighttime logic was not active so the opposite was happening to me  (absence of dark mode icon)
Implemented Solution
I changed the logic to show the opposite icon regardless of what time it was on the user's computer.

[Issue #1531] || fix darkmode toggle bug

---

src/utils/index.ts

resolves #1839
- When users make a new goal or budget inside another goal or budget without filling in certain details, the new goal or budget would just copy those details from the bigger goal or budget inside.
- At first, it was okay for a new goal or budget to copy details like deadlines and time budgets from the one above it.
- Later, we made two separate things: goals and budgets. Goals needed certain details like the due date and duration but didn't care about other details like time budgets, after time, before time.
- But, when you made a goal inside a budget, it would still copy all the details from the budget, even the ones that didn't make sense for a goal. This made the goal seem like a budget, which we didn't want.
- Don't inherit budget-related properties as they are always …

solved can't create a goal inside a budget 

---

vite.config.ts

open-store.io requires all lowercase

open-store.io requires all lowercase

---

src/helpers/GoalController.ts

resolves #1883 
This PR addresses an issue where the user interface becomes unresponsive when a user creates or updates a GoalItem with the hint option enabled. Previously, the modal would remain unresponsive until the server responded with hints, which could lead to a suboptimal user experience.
The changes made in this PR ensure that the UI does not freeze while waiting for server responses, thus maintaining a smooth and responsive experience for the user.

fetch hints from server in background while creating/updating GoalItem

---

src/components/MyTimeComponents/MyTimeline/GoalTiming.tsx
src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx

- **Introduced displayEndTime Prop**: Added a new boolean prop to control the display of the ending time in the GoalTiming component.
- **Conditional Rendering in GoalTiming:** Adjusted rendering to show the end time only if displayEndTime and showTaskOptions are true.
- **Comparison Logic in MyTimeline:** Added logic to determine if the end time should be displayed by comparing it with the next task's start time.
resolves #1794

conditionally render task end times

---

src/api/HintsAPI/ScheduledHintCall.ts
src/api/HintsAPI/index.ts
src/hooks/useApp.tsx
src/models/HintItem.ts
src/models/db.ts

- New Fields for Tracking Hints
**lastCheckDate:** This is a new field that records when we last checked for hints for each goal.
**nextChecktDate:** This field stores string value (daily or weekly) that tells us whether to check for new hints daily or weekly.
- Updates to the Hints API: 
Changed current hints API to use these new fields. 
- Checking for New Hints:
Added a new function that looks for new hints. It checks the hints we just got against the hints we already know to see if there are any changes. Then it updates the nextCheckDate field to now+1day if new hint is found - else the value is set to now+1week. 
- Automatic Hint Checking Schedule:
Set up a new system that decides when to check for hints based on whether we found new hints recently. If we find new hints, we'll check …

Implement Scheduled Hints API Calls

---

package.json

The earlier `npm run lint` script was not working properly. Fixed it by updating the command.

fix: lint script not working locally

---

src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
src/constants/starterGoals.ts
src/helpers/GoalProcessor.ts
src/models/GoalItem.ts

update timeBudget field in goalItem to be budget object or undefined

---

src/translations/i18n.ts

Resolves #1891 
The issue was with **i18next** module. Added the following config in the configuration file of i18next, to resolve the issue.
`nsSeparator: false,
keySeparator: false`

Goal title colon bug fixed

---

vite.config.ts

When trying to publish web app to open-store.io I changed the manifest. This was not necessary and actually gives the wrong name on app startup.
Fixed with this commit.

Fix manifest

---

src/components/GoalsComponents/MyGoalActions/RegularGoalActions.tsx

Removed the confirmation modal when user tries to delete a goal. Instead it shows a toast directly which says "Moved to trash! We'll delete it in 7 days."
Fixes #2054 
Screenshot:

feat: remove confirmation and show toast on goal delete

---

src/global.scss
src/layouts/AppLayout.tsx

Added scrollbar on goals section. User can now scroll through the content. Also, I've added z-index to properly show the footer on overflow.
Closes #2057

fix: show scrollbar on overflow

---

src/api/GoalsAPI/index.ts
src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
src/components/GoalsComponents/GoalConfigModal/components/ArchivedAutoComplete.tsx
src/contexts/parentGoal-context.tsx
src/hooks/useGoalActions.tsx
src/hooks/useGoalStore.tsx

Fixed:
- only show suggestion of archived child goals of a parent
- fix re-render problem
- show different toast msg when suggested goal is added.

restrict archived suggestions to parent goals only and fix subgoal render problem

---

src/Interfaces/index.ts
src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
src/hooks/useScheduler.tsx

show scheduled status in edit modal

---

src/App.tsx

resolves #2115 
The issue was caused due to toast destroy method wrapped inside setTimeout which caused racing conditions. Removed the setTimeout and directly called the destroy method on function call only.

fix: toast not opening correctly for some parts in app
